### ISSUE TITLE
Prevent waterlogged private signs

### ISSUE THREAD

**Issue by ds58** [Ruinscraft/LockettePro#1]
I have noticed people griefing by waterlogging private signs. You cannot worldedit //drain or rollback these and its very annoying

**Comment by drewdorris** [comment]
1. People can do this if they aren't in the town?
2. Does this allow them to remove the sign?

**Comment by ds58** [comment]
1. don't think so
2. nope

**Comment by ds58** [comment]
You can actually drain water logged blocks with WE
https://www.reddit.com/r/admincraft/comments/b1tz78/how_to_replace_all_watery_blocks_113/
